"""Build the BH_V006 production CAD selected by physical coupon tests.

This script imports the proven V006 geometry functions and overrides only the
physical authority dimensions: neck ID26.2 and the numerically largest slide
pair (tab 16.0 x 4.0, receiver 17.1 x 4.8 mm). Existing coupons and nominal
artifacts are not modified.
"""

from __future__ import annotations

import copy
import importlib.util
import json
import subprocess
from collections import Counter
from pathlib import Path
from typing import Any

import cadquery as cq


AUTH_ROOT = Path(__file__).resolve().parents[1]
V006_ROOT = AUTH_ROOT.parent
BASE_SOURCE = V006_ROOT / "source" / "build_bh_v006.py"
AUTHORITY_PATH = AUTH_ROOT / "physical_authority.json"
STEP_DIR = AUTH_ROOT / "step"
STL_DIR = AUTH_ROOT / "stl"
VALIDATION_DIR = AUTH_ROOT / "validation"
REPORT_PATH = AUTH_ROOT / "validation_report_physical_authority.json"

MAIN_NAME = "BH_V006_main_body_PHYSICAL_AUTHORITY_PETG"
COLLAR_NAME = "BH_V006_neck_collar_slide_tab_ID26p2_AUTHORITY_PETG"
ASSEMBLY_NAME = "BH_V006_assembly_PHYSICAL_AUTHORITY"
ASSEMBLY_PREVIEW_NAME = "BH_V006_assembly_PHYSICAL_AUTHORITY_preview"


def load_base_module():
    spec = importlib.util.spec_from_file_location("bh_v006_base", BASE_SOURCE)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import base generator: {BASE_SOURCE}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


BASE = load_base_module()
AUTH = json.loads(AUTHORITY_PATH.read_text(encoding="utf-8"))


def apply_physical_authority() -> None:
    """Override only dimensions selected by the physical tests."""
    BASE.P = copy.deepcopy(BASE.P)
    neck = AUTH["neck"]
    slide = AUTH["slide"]
    BASE.P["neck_collar"]["id"] = neck["neck_id_mm"]
    BASE.P["slide_tab"]["width"] = slide["slide_tab_authority_width_mm"]
    BASE.P["slide_tab"]["thickness"] = slide["slide_tab_authority_thickness_mm"]
    BASE.P["receiver"]["internal_width"] = slide["slide_receiver_authority_width_mm"]
    BASE.P["receiver"]["internal_thickness"] = slide["slide_receiver_authority_thickness_mm"]
    BASE.P["receiver"]["width_clearance"] = slide["resulting_width_clearance_mm"]
    BASE.P["receiver"]["thickness_clearance"] = slide["resulting_thickness_clearance_mm"]
    BASE.P["physical_status"] = copy.deepcopy(AUTH["physical_state"])


def run_git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=V006_ROOT.parents[3],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.rstrip("\n")


def current_git_state() -> dict[str, Any]:
    tracked = run_git("status", "--short", "--untracked-files=no")
    return {
        "branch": run_git("branch", "--show-current"),
        "head": run_git("rev-parse", "HEAD"),
        "tracked_status": tracked.splitlines() if tracked else [],
    }


def export_pair(shape: cq.Shape | cq.Workplane, stem: str) -> tuple[Path, Path]:
    STEP_DIR.mkdir(parents=True, exist_ok=True)
    STL_DIR.mkdir(parents=True, exist_ok=True)
    step_path = STEP_DIR / f"{stem}.step"
    stl_path = STL_DIR / f"{stem}.stl"
    cq.exporters.export(shape, str(step_path))
    cq.exporters.export(
        shape,
        str(stl_path),
        tolerance=BASE.P["mesh_export"]["linear_tolerance"],
        angularTolerance=BASE.P["mesh_export"]["angular_tolerance"],
    )
    return step_path, stl_path


def make_authority_collar() -> tuple[cq.Workplane, dict[str, cq.Workplane]]:
    """Fuse the exact physical S3 coupon tab solid to the ID26.2 collar.

    The nominal collar helper and slide coupon helper historically applied their
    lead chamfers through separate OCC operations. To honor physical authority,
    this production part discards the nominal helper's tab and transfers the
    S3 coupon tab B-rep generated by make_slide_coupon directly.
    """
    slide = AUTH["slide"]
    _, nominal_parts = BASE.make_neck_collar_with_tab(AUTH["neck"]["neck_id_mm"])
    _, s3_parts = BASE.make_slide_coupon(
        slide["slide_receiver_authority_width_mm"],
        slide["slide_receiver_authority_thickness_mm"],
    )
    coupon_tab_aligned = s3_parts["tab"].translate(
        (
            -19.0,
            BASE.P["slide_tab"]["nominal_center_y"],
            BASE.P["slide_tab"]["local_z_min_from_collar_bottom"],
        )
    )
    collar = (
        nominal_parts["ring"]
        .union(nominal_parts["bridge"])
        .union(coupon_tab_aligned)
        .clean()
    )
    return collar, {
        "ring": nominal_parts["ring"],
        "bridge": nominal_parts["bridge"],
        "tab": coupon_tab_aligned,
        "physical_coupon_tab_source": coupon_tab_aligned,
    }


def result(status: str, detail: str) -> dict[str, str]:
    return {"status": status, "detail": detail}


def pass_fail(condition: bool, detail: str) -> dict[str, str]:
    return result("PASS" if condition else "FAIL", detail)


def duplicate_signatures(shape: cq.Shape | cq.Workplane) -> list[tuple[float, ...]]:
    obj = shape.val() if isinstance(shape, cq.Workplane) else shape
    signatures: list[tuple[float, ...]] = []
    for solid in obj.Solids():
        bbox = solid.BoundingBox()
        center = solid.Center()
        signatures.append(
            tuple(
                round(value, 3)
                for value in (
                    solid.Volume(),
                    bbox.xlen,
                    bbox.ylen,
                    bbox.zlen,
                    center.x,
                    center.y,
                    center.z,
                )
            )
        )
    return [signature for signature, count in Counter(signatures).items() if count > 1]


def validate(
    main_body: cq.Workplane,
    main_parts: dict[str, Any],
    collar: cq.Workplane,
    collar_parts: dict[str, cq.Workplane],
    assembly: cq.Compound,
    exports: list[tuple[Path, Path]],
) -> dict[str, Any]:
    checks: dict[str, dict[str, str]] = {}
    slide = AUTH["slide"]
    neck = AUTH["neck"]
    unchanged = AUTH["unchanged_main_body"]

    checks["step_generated"] = pass_fail(
        all(step.exists() and step.stat().st_size > 0 for step, _ in exports),
        "All three production STEP artifacts exist and are non-empty.",
    )
    checks["stl_generated"] = pass_fail(
        all(stl.exists() and stl.stat().st_size > 0 for _, stl in exports),
        "All three production STL artifacts exist and are non-empty.",
    )

    step_reload: dict[str, Any] = {}
    for step, _ in exports:
        loaded = cq.importers.importStep(str(step))
        solids = loaded.solids().vals()
        step_reload[step.name] = {
            "solid_count": len(solids),
            "valid": bool(solids) and all(solid.isValid() for solid in solids),
            "positive_volume": bool(solids) and all(solid.Volume() > 0.0 for solid in solids),
        }
    checks["step_reload"] = pass_fail(
        all(item["valid"] and item["positive_volume"] for item in step_reload.values()),
        "Every production STEP reloads with valid positive-volume solids.",
    )

    mesh_metrics = {stl.name: BASE.stl_metrics(stl) for _, stl in exports}
    checks["stl_watertight"] = pass_fail(
        all(item["watertight"] for item in mesh_metrics.values()),
        "All production STL meshes are watertight.",
    )
    checks["non_manifold_edge_zero"] = pass_fail(
        all(item["non_manifold_edges"] == 0 for item in mesh_metrics.values()),
        "Every STL has zero non-manifold edges after vertex merge.",
    )
    checks["positive_mesh_volume"] = pass_fail(
        all(not item["negative_volume"] for item in mesh_metrics.values()),
        "Every STL has positive signed volume.",
    )

    shapes = {MAIN_NAME: main_body, COLLAR_NAME: collar, ASSEMBLY_NAME: assembly}
    duplicates = {name: duplicate_signatures(shape) for name, shape in shapes.items()}
    checks["no_duplicate_solid"] = pass_fail(
        not any(duplicates.values()),
        "No production artifact contains duplicated solid signatures.",
    )

    assembly_z = BASE.P["assembly"]["nominal_collar_bottom_global_z"]
    collar_placed = collar.translate((0.0, 0.0, assembly_z))
    nominal_intersection = main_body.intersect(collar_placed).val().Volume()
    checks["nominal_assembly_intersection_zero"] = pass_fail(
        nominal_intersection < 1.0e-4,
        f"Main/collar nominal intersection = {nominal_intersection:.6f} mm3.",
    )

    insertion_path: list[dict[str, float]] = []
    insertion_clear = True
    for dz in (30.0, 24.0, 18.0, 12.0, 6.0, 0.0):
        moved = collar.translate((0.0, 0.0, assembly_z + dz))
        intersection = main_body.intersect(moved).val().Volume()
        insertion_path.append(
            {"offset_z_mm": dz, "intersection_volume_mm3": round(intersection, 6)}
        )
        insertion_clear = insertion_clear and intersection < 1.0e-4
    checks["top_down_linear_insertion"] = pass_fail(
        insertion_clear,
        "The straight top-down insertion path from +30 mm to nominal seat is collision-free.",
    )

    floor = main_parts["receiver_parts"]["floor"]
    floor_bbox = BASE.bbox_dict(floor)
    checks["receiver_bottom_stop"] = pass_fail(
        floor.val().Volume() > 0.0
        and abs(floor_bbox["zlen"] - BASE.P["receiver"]["bottom_stop_thickness"]) < 0.01,
        f"Receiver has a closed {floor_bbox['zlen']:.3f} mm bottom stop.",
    )

    id_gauge = (
        cq.Workplane("XY")
        .circle(neck["neck_id_mm"] / 2.0 - 0.01)
        .extrude(neck["collar_height_mm"])
    )
    id_overlap = collar_parts["ring"].intersect(id_gauge).val().Volume()
    checks["production_neck_id26p2"] = pass_fail(
        BASE.P["neck_collar"]["id"] == 26.2 and id_overlap < 1.0e-4,
        "Production collar is generated from the unchanged tested C-ring function at ID26.2 mm.",
    )

    tab_bbox = BASE.bbox_dict(collar_parts["tab"])
    checks["physical_tab_dimensions_exact"] = pass_fail(
        BASE.P["slide_tab"]["width"] == slide["slide_tab_authority_width_mm"]
        and BASE.P["slide_tab"]["thickness"] == slide["slide_tab_authority_thickness_mm"]
        and abs(tab_bbox["xlen"] - slide["slide_tab_authority_width_mm"]) < 0.05
        and abs(tab_bbox["ylen"] - slide["slide_tab_authority_thickness_mm"]) < 0.05,
        f"Production construction gauge is exactly {BASE.P['slide_tab']['width']:.1f} x {BASE.P['slide_tab']['thickness']:.1f} mm; OCC tolerance-expanded B-rep bbox = {tab_bbox['xlen']:.3f} x {tab_bbox['ylen']:.3f} mm.",
    )

    # The production tab and coupon tab are built by the same function. Compare solids after alignment.
    _, coupon_parts = BASE.make_slide_coupon(
        slide["slide_receiver_authority_width_mm"],
        slide["slide_receiver_authority_thickness_mm"],
    )
    coupon_tab_aligned = coupon_parts["tab"].translate(
        (
            -19.0,
            BASE.P["slide_tab"]["nominal_center_y"],
            BASE.P["slide_tab"]["local_z_min_from_collar_bottom"],
        )
    )
    tab_delta = collar_parts["tab"].cut(coupon_tab_aligned).val().Volume()
    tab_delta += coupon_tab_aligned.cut(collar_parts["tab"]).val().Volume()
    production_tab_volume = collar_parts["tab"].val().Volume()
    coupon_tab_volume = coupon_tab_aligned.val().Volume()
    tab_volume_delta = abs(production_tab_volume - coupon_tab_volume)
    tab_symmetric_difference_ratio = tab_delta / max(production_tab_volume, coupon_tab_volume)
    checks["physical_coupon_tab_geometry_transferred"] = pass_fail(
        tab_volume_delta < 0.01 and tab_symmetric_difference_ratio < 0.01,
        f"Production and S3 coupon tabs use the same constructor, dimensions, R1.2 corners, and 1.0/0.8 mm lead chamfers. Volume delta = {tab_volume_delta:.6f} mm3; OCC boolean symmetric-difference ratio = {tab_symmetric_difference_ratio:.6%}.",
    )

    rec_parts = main_parts["receiver_parts"]
    left_bbox = BASE.bbox_dict(rec_parts["left_rail"])
    right_bbox = BASE.bbox_dict(rec_parts["right_rail"])
    back_bbox = BASE.bbox_dict(rec_parts["back_wall"])
    lip_bbox = BASE.bbox_dict(rec_parts["left_lip"])
    measured_internal_width = right_bbox["xmin"] - left_bbox["xmax"]
    measured_internal_thickness = lip_bbox["ymin"] - back_bbox["ymax"]
    checks["physical_receiver_dimensions_exact"] = pass_fail(
        abs(measured_internal_width - slide["slide_receiver_authority_width_mm"]) < 0.01
        and abs(measured_internal_thickness - slide["slide_receiver_authority_thickness_mm"]) < 0.01,
        f"Measured production receiver cavity = {measured_internal_width:.3f} x {measured_internal_thickness:.3f} mm.",
    )
    checks["physical_receiver_guide_shape_transferred"] = pass_fail(
        BASE.P["receiver"]["front_stem_slot_width"] == slide["front_stem_slot_width_mm"]
        and BASE.P["receiver"]["lead_in_chamfer"] == slide["entrance_chamfer_mm"]
        and BASE.P["receiver"]["insertion_length"] == slide["insertion_length_mm"],
        "Production receiver reuses the tested coupon make_receiver guide, 10.8 mm stem slit, 1.0 mm top lead-in, and vertical insertion direction without added clearance.",
    )

    cup_bbox = BASE.bbox_dict(main_parts["cup"])
    cavity_bbox = BASE.bbox_dict(main_parts["cup_parts"]["cavity_lower"])
    checks["cup_height_94_unchanged"] = pass_fail(
        abs(cup_bbox["zlen"] - unchanged["cup_height_mm"]) < 0.05,
        f"Cup B-rep Z extent = {cup_bbox['zlen']:.3f} mm.",
    )
    checks["cup_72x72_r11_unchanged"] = pass_fail(
        abs(cavity_bbox["xlen"] - unchanged["cup_inner_x_mm"]) < 0.01
        and abs(cavity_bbox["ylen"] - unchanged["cup_inner_y_mm"]) < 0.01
        and BASE.P["cup"]["inner_corner_radius"] == unchanged["cup_corner_r_mm"],
        f"Functional cavity = {cavity_bbox['xlen']:.3f} x {cavity_bbox['ylen']:.3f} mm / R{BASE.P['cup']['inner_corner_radius']:.1f}.",
    )

    drain_count = len(BASE.P["cup"]["drain_hole_centers_xy"])
    checks["drains_unchanged"] = pass_fail(
        drain_count == unchanged["drain_hole_count"]
        and BASE.P["cup"]["drain_hole_diameter"] == unchanged["drain_hole_diameter_mm"],
        f"Drain pattern remains phi{BASE.P['cup']['drain_hole_diameter']:.1f} x {drain_count}.",
    )

    rope_gauges: list[dict[str, float]] = []
    rope_clear = True
    for x, z in main_parts["rope_slot_centers"]:
        gauge = (
            cq.Workplane("XY")
            .circle(unchanged["rope_diameter_mm"] / 2.0)
            .extrude(30.0)
            .rotate((0, 0, 0), (1, 0, 0), 90)
            .translate((x, -30.0, z))
        )
        overlap = main_body.intersect(gauge).val().Volume()
        rope_clear = rope_clear and overlap < 1.0e-4
        rope_gauges.append(
            {"center_x_mm": x, "center_z_mm": z, "intersection_volume_mm3": round(overlap, 6)}
        )
    checks["rope_slots_unchanged"] = pass_fail(
        rope_clear
        and len(main_parts["rope_slot_centers"]) == unchanged["rope_slot_count"]
        and BASE.P["rope"]["slot_width"] == unchanged["rope_slot_mm"][0]
        and BASE.P["rope"]["slot_height"] == unchanged["rope_slot_mm"][1]
        and BASE.P["rope"]["slot_center_spacing"] == unchanged["rope_slot_center_distance_mm"],
        "Two 8 x 14 mm slots at 46 mm centers pass phi4.8 mm gauges.",
    )

    cap_diameter = BASE.P["assembly"]["cap_rotation_clearance_diameter"]
    cap = (
        cq.Workplane("XY")
        .circle(cap_diameter / 2.0)
        .extrude(14.0)
        .translate((0.0, 0.0, assembly_z + neck["collar_height_mm"] + 0.5))
    )
    cap_overlap = main_body.intersect(cap).val().Volume()
    cap_overlap += collar_placed.intersect(cap).val().Volume()
    checks["cap_rotation_envelope"] = pass_fail(
        cap_overlap < 1.0e-4,
        f"Phi{cap_diameter:.1f} mm cap rotation envelope overlap = {cap_overlap:.6f} mm3.",
    )

    tab_bottom = assembly_z + BASE.P["slide_tab"]["local_z_min_from_collar_bottom"]
    float_mm = tab_bottom - main_parts["receiver_cavity_z_min"]
    float_low, float_high = slide["acceptable_float_range_mm"]
    checks["assembly_slide_float_positive"] = pass_fail(
        float_mm > 0.0,
        f"Measured assembly slide float = {float_mm:.3f} mm (>0).",
    )
    checks["assembly_slide_float_target_range"] = pass_fail(
        float_low <= float_mm <= float_high,
        f"Measured float {float_mm:.3f} mm is within {float_low:.1f}--{float_high:.1f} mm.",
    )
    checks["cup_bottom_primary_load_support"] = pass_fail(
        float_mm > 0.0
        and BASE.P["assembly"]["bottle_support_plane_z"] == BASE.P["cup"]["bottom_thickness"],
        f"Bottle support plane is the {BASE.P['cup']['bottom_thickness']:.1f} mm cup floor; the slide is unloaded by the positive float.",
    )

    start_git = AUTH["start_git_state"]
    end_git = current_git_state()
    checks["git_branch_head_unchanged"] = pass_fail(
        start_git["branch"] == end_git["branch"] and start_git["head"] == end_git["head"],
        f"Start/end branch={end_git['branch']}, HEAD={end_git['head']}.",
    )
    checks["preexisting_tracked_status_unchanged"] = pass_fail(
        start_git["tracked_status"] == end_git["tracked_status"],
        "The pre-existing tracked status snapshot is unchanged; this generator performs no Git mutation.",
    )

    physical_status = {
        name: result(status, "Physical state supplied by the user; CAD does not override it.")
        for name, status in AUTH["physical_state"].items()
    }

    hard_failures = [name for name, item in checks.items() if item["status"] == "FAIL"]
    counts = Counter(item["status"] for item in checks.values())
    counts.update(item["status"] for item in physical_status.values())
    return {
        "project": AUTH["project"],
        "overall_cad_status": "PASS" if not hard_failures else "FAIL",
        "hard_failures": hard_failures,
        "authority": {
            "neck": "ID26.2",
            "slide_candidate": slide["slide_authority"],
            "slide_semantic": slide["authority_semantic"],
            "tab_mm": [
                slide["slide_tab_authority_width_mm"],
                slide["slide_tab_authority_thickness_mm"],
            ],
            "receiver_mm": [
                slide["slide_receiver_authority_width_mm"],
                slide["slide_receiver_authority_thickness_mm"],
            ],
            "measured_float_mm": round(float_mm, 4),
        },
        "summary_counts": dict(sorted(counts.items())),
        "cad_checks": checks,
        "physical_state": physical_status,
        "git": {"start": start_git, "end": end_git},
        "step_reload": step_reload,
        "stl_metrics": mesh_metrics,
        "geometry": {
            "main_body_bbox_mm": BASE.bbox_dict(main_body),
            "cup_bbox_mm": cup_bbox,
            "functional_cavity_bbox_mm": cavity_bbox,
            "production_tab_bbox_mm": tab_bbox,
            "measured_receiver_internal_mm": [
                round(measured_internal_width, 4),
                round(measured_internal_thickness, 4),
            ],
            "nominal_intersection_mm3": round(nominal_intersection, 6),
            "insertion_path": insertion_path,
            "rope_gauge_checks": rope_gauges,
            "cap_envelope_intersection_mm3": round(cap_overlap, 6),
            "slide_float_mm": round(float_mm, 4),
            "coupon_to_production_tab_symmetric_difference_mm3": round(tab_delta, 6),
            "coupon_to_production_tab_symmetric_difference_ratio": round(
                tab_symmetric_difference_ratio, 8
            ),
            "coupon_to_production_tab_volume_delta_mm3": round(tab_volume_delta, 6),
            "duplicate_solid_signatures": {
                name: [list(signature) for signature in signatures]
                for name, signatures in duplicates.items()
            },
        },
        "physical_authority_note": "Physical fit results are treated as higher authority than nominal label semantics. No clearance was added beyond the selected S3 coupon dimensions.",
    }


def main() -> None:
    apply_physical_authority()
    STEP_DIR.mkdir(parents=True, exist_ok=True)
    STL_DIR.mkdir(parents=True, exist_ok=True)
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)

    main_body, main_parts = BASE.make_main_body()
    collar, collar_parts = make_authority_collar()
    assembly_z = BASE.P["assembly"]["nominal_collar_bottom_global_z"]
    collar_placed = collar.translate((0.0, 0.0, assembly_z))
    assembly = cq.Compound.makeCompound([main_body.val(), collar_placed.val()])

    exports: list[tuple[Path, Path]] = []
    exports.append(export_pair(main_body, MAIN_NAME))
    exports.append(export_pair(collar, COLLAR_NAME))

    assembly_step = STEP_DIR / f"{ASSEMBLY_NAME}.step"
    assembly_stl = STL_DIR / f"{ASSEMBLY_PREVIEW_NAME}.stl"
    cq.exporters.export(assembly, str(assembly_step))
    cq.exporters.export(
        assembly,
        str(assembly_stl),
        tolerance=BASE.P["mesh_export"]["linear_tolerance"],
        angularTolerance=BASE.P["mesh_export"]["angular_tolerance"],
    )
    exports.append((assembly_step, assembly_stl))

    report = validate(main_body, main_parts, collar, collar_parts, assembly, exports)
    REPORT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (VALIDATION_DIR / "artifact_manifest_physical_authority.json").write_text(
        json.dumps(
            {
                "step": [str(path.relative_to(AUTH_ROOT)).replace("\\", "/") for path, _ in exports],
                "stl": [str(path.relative_to(AUTH_ROOT)).replace("\\", "/") for _, path in exports],
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "overall_cad_status": report["overall_cad_status"],
                "hard_failures": report["hard_failures"],
                "summary_counts": report["summary_counts"],
                "slide_float_mm": report["authority"]["measured_float_mm"],
            }
        )
    )


if __name__ == "__main__":
    main()
