"""Central dimensions for Paddy Vacuum Siphon Primer v0.1.

Units are millimetres unless noted.  This file intentionally keeps hardware-
dependent hole sizes grouped so they can be calibrated against purchased parts.
"""

# Release gate
DESIGN_STATUS = "PROTOTYPE_ONLY"
MANUFACTURING_RELEASE = False
FIELD_DEPLOYMENT_STATUS = "NOT_APPROVED"

# Vacuum design limits
MAX_OPERATING_VACUUM_KPA = 20.0
PROOF_TEST_VACUUM_KPA = 30.0

# Water trap body
TANK_INNER_DIAMETER = 90.0
TANK_WALL = 5.0
TANK_OUTER_DIAMETER = TANK_INNER_DIAMETER + 2.0 * TANK_WALL
TANK_INNER_HEIGHT = 150.0
TANK_BASE_THICKNESS = 6.0
TANK_BODY_HEIGHT = TANK_BASE_THICKNESS + TANK_INNER_HEIGHT
TANK_FLANGE_DIAMETER = 126.0
TANK_FLANGE_THICKNESS = 10.0
TANK_TOTAL_HEIGHT = TANK_BODY_HEIGHT + TANK_FLANGE_THICKNESS
TANK_VERTICAL_RIB_COUNT = 8
TANK_VERTICAL_RIB_WIDTH = 5.0
TANK_VERTICAL_RIB_DEPTH = 4.0

# Lid and tank bolting
TANK_LID_DIAMETER = 126.0
TANK_LID_THICKNESS = 8.0
TANK_LID_DOME_HEIGHT = 5.0
TANK_BOLT_COUNT = 8
TANK_BOLT_HOLE_DIAMETER = 4.5
TANK_BOLT_CIRCLE = 112.0
TANK_GASKET_OUTER_DIAMETER = 116.0
TANK_GASKET_INNER_DIAMETER = 94.0

# Lid ports.  All penetrations are on the removable lid in CAD v0.1.
BULKHEAD_NOMINAL_HOLE = 22.0
BULKHEAD_INLET_X = 31.0
BULKHEAD_OUTLET_X = 0.0
GAUGE_HOLE_DIAMETER = 12.0
GAUGE_PORT_X = -32.0
DIP_TUBE_OUTER_DIAMETER = 16.0
DIP_TUBE_INNER_DIAMETER = 12.0
DIP_TUBE_LENGTH = 108.0

# Baffle
BAFFLE_WIDTH = 60.0
BAFFLE_HEIGHT = 75.0
BAFFLE_THICKNESS = 3.0
BAFFLE_FOOT_WIDTH = 12.0
BAFFLE_FOOT_LENGTH = 20.0

# Bellows -- corrected clearance version
BELLOWS_MAX_DIAMETER = 172.0
BELLOWS_MIN_DIAMETER = 142.0
BELLOWS_FREE_HEIGHT = 132.0
BELLOWS_COMPRESSED_HEIGHT = 58.0
BELLOWS_CONVOLUTION_COUNT = 7
BELLOWS_WALL = 1.6
BELLOWS_ROOT_WALL = 2.0
BELLOWS_FLANGE_DIAMETER = 200.0
BELLOWS_FLANGE_THICKNESS = 3.2
BELLOWS_BOLT_COUNT = 8
BELLOWS_BOLT_HOLE_DIAMETER = 4.8
BELLOWS_BOLT_CIRCLE = 188.0

# Bellows plates
BASE_SIZE = 230.0
BASE_THICKNESS = 10.0
FOOT_PLATE_SIZE = 230.0
FOOT_PLATE_THICKNESS = 10.0
CLAMP_RING_OUTER_DIAMETER = 200.0
CLAMP_RING_INNER_DIAMETER = 176.0
CLAMP_RING_THICKNESS = 6.0

# Air ports in the fixed base
AIR_PORT_HOLE_DIAMETER = 22.0
AIR_PORT_X = 30.0

# Guide system -- moved outside the corrected bellows flange
GUIDE_ROD_COUNT = 3
GUIDE_ROD_DIAMETER = 6.0
GUIDE_HOLE_DIAMETER = 7.2
GUIDE_ROD_CIRCLE = 212.0
GUIDE_BUSHING_OUTER_DIAMETER = 12.0
GUIDE_BUSHING_LENGTH = 16.0
GUIDE_BUSHING_FLANGE_DIAMETER = 18.0
GUIDE_BUSHING_FLANGE_THICKNESS = 3.0

# Foot pad
FOOT_PAD_LENGTH = 150.0
FOOT_PAD_WIDTH = 100.0
FOOT_PAD_THICKNESS = 3.0

# Tank stand
STAND_SIZE = 140.0
STAND_BASE_THICKNESS = 8.0
STAND_CRADLE_INNER_DIAMETER = 100.5
STAND_CRADLE_OUTER_DIAMETER = 114.0
STAND_CRADLE_HEIGHT = 22.0
STAND_DRAIN_CLEARANCE_DIAMETER = 35.0
STAND_MOUNT_HOLE_DIAMETER = 5.5
STAND_MOUNT_OFFSET = 56.0

# Adapter defaults; confirm against purchased hardware before manufacturing
CHECK_VALVE_OUTER_DIAMETER = 28.0
CHECK_VALVE_BRACKET_CLEARANCE = 0.5
HOSE_OUTER_DIAMETER = 16.0

# Mesh/CAD resolution
REVOLVE_SAMPLES = 120
BELLOW_PROFILE_SAMPLES_PER_CONVOLUTION = 12
