"""Contract tests for PS-BBOX-LID-WIRING-CHIMNEY-V001."""
import importlib.util,json
from pathlib import Path
from cadquery import importers
LANE=Path(__file__).resolve().parents[1];p=LANE/"build_bbox_lid_wiring_chimney_v001.py"
s=importlib.util.spec_from_file_location("b",p);assert s and s.loader;b=importlib.util.module_from_spec(s);s.loader.exec_module(b)
n=0
def ck(x,l):
 global n;n+=1
 if not x:raise AssertionError(l)
repo=b.guard(True);d=json.loads((LANE/"design_parameters.json").read_text(encoding="utf-8"));v=json.loads((LANE/"validation_report.json").read_text(encoding="utf-8"))
for k in ("root","branch","head","staged_zero","dirty_preserved","outside_preserved","authority_4","protected_9","parent_lid_hash","scope","complete"):ck(repo["checks"][k],k)
ck(d["measurements"]["gland_male_thread_od_mm"]==14.9,"thread")
ck(d["measurements"]["cable_od_mm"]==9.6,"cable")
ck(d["measurements"]["gland_standard"]=="NOT_INFERRED","standard")
ck(d["architecture"]["selected"]=="BBOX_LID_INTEGRATED_WIRING_CHIMNEY","architecture")
ck(d["architecture"]["chimney_base_joint_count"]==0,"joint")
ck(d["architecture"]["separate_base_gasket"] is False and d["architecture"]["service_cap"] is False,"interfaces")
ck(d["architecture"]["orientation"]=="HORIZONTAL_TOWARD_CBOX","orientation")
ck(d["gland"]["mount_hole_candidate_mm"]==15.5,"hole")
ck([x["hole_d_mm"] for x in d["gland"]["coupon_candidates"]]==[15.2,15.5,15.8],"coupon")
ck([x["notches"] for x in d["gland"]["coupon_candidates"]]==[1,2,3],"notches")
ck(d["gland"]["pad_added_thickness_mm"]>=5,"pad")
ck(d["gland"]["pad_surface"]=="PLANAR","flat")
ck(d["chimney"]["external_xyz_mm"]==[50.0,45.0,60.0],"chimney")
ck(d["chimney"]["internal_xy_mm"]==[42.0,37.0],"internal")
ck(min(d["chimney"]["internal_xy_mm"])>=34,"internal min")
ck(d["chimney"]["gland_center_above_lid_top_mm"]==35,"center")
ck(d["chimney"]["hood_width_mm"]==36,"hood width")
ck(d["chimney"]["hood_projection_mm"]==10,"hood")
ck(d["chimney"]["hood_bottom_open"] and d["chimney"]["water_trap_count"]==0,"drain")
ck(d["waterline"]["relative_margin_mm"]==30,"margin")
ck("PHYSICAL_HOLD" in d["waterline"]["absolute_waterline_clearance"],"absolute hold")
ck(d["tool_access"]["external_radial_keepout_d_mm"]>=35,"external D")
ck(d["tool_access"]["external_service_depth_mm"]>=35,"depth")
ck(d["tool_access"]["lid_underside_access"],"underside")
ck(d["cable"]["hard_bend_radius_candidate_mm"]>=28.8,"bend hard")
ck(d["cable"]["target_bend_radius_mm"]>=38.4,"bend target")
ck(d["cable"]["service_length_mm"]==900 and d["cable"]["drip_loop"],"route")
ck(d["freeze"]["gasket_loop_change"]==0,"gasket freeze")
ck(d["freeze"]["seal_land_change"]==0,"seal freeze")
ck(d["freeze"]["fastener_pattern_change"]==0,"fastener freeze")
ck(d["service"]["lid_chimney_removed_together"],"service")
ck(d["service"]["battery_extraction_permanent_collision"]==0,"battery")
ck(d["boundaries"]["primary"]==["BBOX_SHELL","LID","RUBBER_CORD_GASKET"],"primary")
ck(d["boundaries"]["gland_continuous_full_submersion"]=="NOT_PRIMARY_REQUIREMENT","firewall")
ck(d["print"]["support_on_seal_face"]==0,"support")
a=v["analysis"];ck(a["lid_valid"] and a["lid_solids"]==1,"lid solid")
ck(a["seal_land_delta_mm3"]==0,"seal geometry")
ck(a["fastener_pattern_delta_mm3"]==0,"fastener geometry")
ck(a["external_tool_lid_intersection_mm3"]==0,"tool clear")
ck(a["external_tool_hood_intersection_mm3"]==0,"hood clear")
ck(a["a1_envelope_pass"],"A1")
ck(len(b.EXPECTED)==39 and len((LANE/"COMMIT_PATHS.txt").read_text(encoding="utf-8").splitlines())==39,"paths")
ck(len(b.STEPS)==7 and len(b.STLS)==2 and len(b.SVGS)==10,"counts")
for r in b.STEPS:
 sh=importers.importStep(str(LANE/r));ck(sh.val().isValid(),r);ck(len(sh.solids().vals())>0,r+" solids")
for r in b.STLS:
 m=b.v002.v001.mesh_metrics(LANE/r);ck(m["reload"]=="PASS" and m["watertight"] and m["manifold"],r);ck(m["bad_edge_count"]==0 and m["degenerate_triangle_count"]==0,r+" edges")
for r in b.SVGS:
 t=(LANE/r).read_text(encoding="utf-8");ck(t.startswith("<svg"),r);ck(b.VERSION in t,r+" id")
ck(v["pass_count"]==v["check_count"],"validation")
ck(v["reproducibility"]["status"]=="PASS","repro")
ck("PHYSICAL_VALIDATION_PENDING" in v["status"],"status")
print(f"AUTOMATED_TESTS={n}/{n} PASS")
print("STEP_RELOAD=7/7 PASS")
print("STL_WATERTIGHT_MANIFOLD=2/2 PASS")
print("PROTECTED_TREES=9/9 UNCHANGED")
print("FINAL=PASS")
