"""Machine-readable Phase 3I-F authority and pending physical decisions."""

PHASE3IF_PROCESS_NAME = "PHASE_3IF_NON_ROTATING_DRY_CORE_FRAME_INTERFACE_FOR_30_DEGREE_DIRECT_DROP_STACK"
PHASE3IF_STATUS = "CAD_COMPLETE_PHYSICAL_FRAME_VALIDATION_PENDING"
PHASE3IF_STATUS_LINES = (
    "FRAME_CLOCKING_CONFLICT_RECORDED",
    "NON_ROTATING_DRY_CORE_FRAME_IMPLEMENTED",
    "THIRTY_DEGREE_STAGE_ROTATION_PRESERVED",
    "FIVE_STAGE_DRY_CORE_REFERENCE_READY",
    "DIRECT_DROP_CORRIDORS_CLEAR_OF_FRAME",
    "CENTERING_PUCK_FIT_COUPONS_READY",
    "MAST_PHYSICAL_MEASUREMENT_PENDING",
    "BAMBU_STUDIO_REVIEW_PENDING",
    "PHYSICAL_FRAME_VALIDATION_PENDING",
    "FULL_STAGE_PRINT_PROHIBITED",
)

STAGE_RELATIVE_ROTATION_DEG = 30.0
STAGE_ABSOLUTE_ROTATIONS_DEG = (0.0, 30.0, 60.0, 90.0, 120.0)
LEGACY_REAR_FIXING_STATUS = "SUPERSEDED_BY_NON_ROTATING_DRY_CORE_FRAME"
PHASE3IE_60DEG_PARTIAL_STATUS = "ABORTED_PARTIAL_SOURCE"

FRAME_PHYSICAL_PASS = False
MAST_STRENGTH_PASS = False
CLOCKING_GUIDE_PHYSICAL_PASS = False
DIRECT_DROP_CAPTURE_PASS = False
FULL_STAGE_PRINT_APPROVED = False
PRODUCTION_READY = False

