"""Machine-readable Phase 3I-D state and frozen hydraulic history."""

from __future__ import annotations


PHASE3ID_PROCESS_NAME = "PHASE_3ID_POSITIVE_INTERSTAGE_OPEN_CASCADE_INTERFACE_AND_TWO_STAGE_HYDRAULIC_VALIDATION_COUPON"
PHASE3ID_STATUS = "CAD_COMPLETE_PHYSICAL_HYDRAULIC_VALIDATION_PENDING"
PHASE3ID_STATUS_LINES = (
    "PHASE3IC_INTERSTAGE_PATH_DEFECT_RECORDED",
    "POSITIVE_OPEN_CASCADE_IMPLEMENTED",
    "TWO_STAGE_CASCADE_REFERENCE_READY",
    "TWO_STAGE_CASCADE_COUPONS_READY",
    "UPDATED_PROGRESSIVE_DIAGNOSTIC_STLS_READY",
    "BAMBU_STUDIO_REVIEW_PENDING",
    "HYDRAULIC_FLOW_TEST_PENDING",
    "FULL_STAGE_PRINT_PROHIBITED",
)

PHASE3IC_INTERSTAGE_TRANSFER = {
    "intended_route": "PRESENT",
    "upper_overflow_structure": "PRESENT",
    "lower_positive_receiver": "ABSENT",
    "guaranteed_transfer": "FAIL",
    "central_hole_as_water_route": "PROHIBITED",
    "status": "HYDRAULIC_INTERSTAGE_PATH_INCOMPLETE",
}

PHASE3IC_FROZEN_BASELINE = {
    "status": "HISTORICAL_HYDRAULICALLY_INCOMPLETE",
    "official_artifact_count": 46,
    "mutation": "PROHIBITED",
    "print": "PROHIBITED",
    "preserved_design_assets": [
        "KEEPER_V2",
        "SIX_COMPLETE_RETENTION_LUGS",
        "CRADLE",
        "REAL_ANNULAR_SUMP",
        "CONTINUOUS_INNER_DAM",
        "PORT_ENVELOPE",
        "D01",
        "D02",
        "D03",
    ],
    "historical_hydraulically_incomplete": ["D04", "D05", "CORRECTED_FULL"],
}

MODULE_HEIGHT_MM = 170.0
NOMINAL_BODY_OUTER_DIAMETER_MM = 200.0
MAXIMUM_TOTAL_XY_ENVELOPE_MM = 238.0
MAXIMUM_REAR_RADIUS_MM = 118.5
PORT_RECESS_MM = 2.0
SELECTED_WATER_SURFACE_Z_MM = 26.0
SELECTED_WATER_DEPTH_MM = 22.0
CENTRAL_HOLE_WATER_ROUTE = False

BAMBU_STUDIO_REVIEW = "PENDING"
HYDRAULIC_FLOW_TEST = "PENDING"
INTERSTAGE_TRANSFER_PASS = False
FLOATING_REGION_SOURCE_IDENTIFIED = False
FLOATING_REGION_FIXED = False
FULL_STAGE_PRINT_APPROVED = False
SUMP_WATERTIGHT = False
OVERFLOW_PASS = False
NETPOT_RETENTION_PASS = False
PRODUCTION_READY = False

